complete --command ws -f -a stu --description "iCloud Drive/STU" --condition "__fish_use_subcommand"
complete --command ws -f -a play --description "Playground" --condition "__fish_use_subcommand"
complete --command ws -f -a icloud --description "iCloud" --condition "__fish_use_subcommand"
complete --command ws -f -a config --description "~/.config" --condition "__fish_use_subcommand"
complete --command ws -f -a devkit --description "~/.devkit" --condition "__fish_use_subcommand"
